"""Editor stub for blender_wrapper — used only for IDE type resolution (no runtime behavior)."""

from typing import Any, Dict, List, Optional

def ensure_collection(name: str) -> Optional[object]: ...
def get_object_by_name(name: str) -> Optional[object]: ...
def create_primitive(primitive: str="CUBE", name: str="Primitive", location=None, rotation=None, scale=None, color=None, collection=None, dry_run: bool=False) -> Optional[str]: ...
def move_object(name: str, location, dry_run: bool=False): ...
def rotate_object(name: str, rotation, dry_run: bool=False): ...
def scale_object(name: str, scale, dry_run: bool=False): ...
def delete_object(name: str, dry_run: bool=False): ...
def add_modifier_to_object(obj_name: str, modifier_type: str, params: Dict[str, Any]=None, dry_run: bool=False): ...
def apply_modifier_stack(obj_name: str, stack: List[Dict[str, Any]], dry_run: bool=False): ...
def apply_material_to_object(obj_name: str, material_spec: Dict[str, Any], dry_run: bool=False): ...
def apply_shader_to_object(obj_name: str, shader_spec: Dict[str, Any], dry_run: bool=False): ...
def import_image_as_plane(image_path: str, name: str="ImagePlane", location=None, scale=None, collection: Optional[str]=None, dry_run: bool=False) -> Optional[str]: ...
def apply_physics_preset(obj_name: str, preset: str, params: Dict[str, Any]=None, dry_run: bool=False): ...
def apply_animation(obj_name: str, anim_spec: Dict[str, Any], dry_run: bool=False): ...
def apply_geometry_template(obj_name: str, template: str, params: Dict[str, Any]=None, dry_run: bool=False): ...
def list_outbox(outdir: str): ...
